[package]
name = "clips"
version = "0.1.0"
authors = ["Jonas Matser <crates@jonasmatser.nl>"]

[dependencies]
clips-sys = { git = "https://github.com/mtsr/clips-sys" }
failure = "0.1.3"
bitflags = "1.0.4"